project:
  type: book
  output-dir: docs

book:
  title: "Bioestadística Aplicada e Interactiva: Guía con R, Python y Aplicaciones Shiny"
  author: "Deiver Suárez Gómez"
  date: "6/19/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - 01_datos.qmd
    - 02_estadistica_descriptiva.qmd
    - 03_probabilidades.qmd
    - 04_inferencia.qmd
    - 05_regresion.qmd
    - references.qmd

format:
  html:
    number-sections: true
    toc-depth: 2
    theme: cosmo
    lang: es
  epub:
    toc-depth: 2
    number-sections: true
    lang: es

lang: es


#quarto preview      Vista previa (modo directo)	Terminal o terminal RStudio
# quarto_preview()   Vista previa del libro	Consola RStudio (R)
#install.packages("quarto")  Instalar paquete en R	Consola RStudio
#quarto render --to pdf  Compilar en PDF	Terminal
